name: localwp
recipe: wordpress
config:
  webroot: wordpress
  php: '7.4'
# services:
#   phpmyadmin:
#     type: phpmyadmin
#     hosts:
#       - database
# proxy:
#   phpmyadmin:
#     - phpmyadmin.localwp.lndo.site
tooling:
  cc:
    service: appserver
    description: Clear WordPress cache
    cmd: wp cache flush
    dir: /app/wordpress/
